@host = http://localhost:8082

POST {{host}}/api/auth/signup
Content-Type: application/json

{
  "loginId": "u",
  "password": "u",
  "name": "김철수",
  "phone": "010-1234-5672",
  "email": "test@nhn2.com",
  "birthDate": "1999-01-02",
  "gender": "FEMALE",
  "role": "USER"
}


### 로그인
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "loginId": "u",
  "password": "u"
}

> {%
    // 응답에서 accessToken을 꺼내서 'access_token'이라는 이름으로 저장합니다.
    client.global.set("access_token", response.body.accessToken);

    // 잘 저장됐는지 로그로 확인
    client.log("저장된 토큰: " + client.global.get("access_token"));
%}


### 3. 내 포인트 잔액 조회
GET http://localhost:8082/api/points/balance
Authorization: Bearer {{access_token}}


###  로그아웃
POST {{host}}/api/auth/logout
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {%
    client.test("로그아웃 성공 확인", function() {
        client.assert(response.status === 200, "응답 코드가 200 OK가 아닙니다.");
    });
%}



### 1 결제 - 포인트 사용
# 기대 결과: 200 OK / DB 잔액 9000원
POST http://localhost:9002/internal/points/use
Content-Type: application/json

{
  "memberId": 1,
  "orderId": 1,
  "amount": 1000
}

### 1.1 결제 취소 - 포인트 복구
# 기대 결과: 200 OK / DB 잔액 다시 10000원
POST http://localhost:9002/internal/points/revert
Content-Type: application/json

{
  "memberId": 1,
  "orderId": 1,
  "amount": 1000
}

### 1.2 잔액 부족 테스트 (예외 발생)
# 기대 결과: 500 Error
POST http://localhost:9002/internal/points/use
Content-Type: application/json

{
  "memberId": 1,
  "orderId": 1,
  "amount": 1000
}



### 2 주문 적립 (등급 비율)
POST http://localhost:9002/internal/points/earn
Content-Type: application/json

{
  "memberId": 1,
  "eventType": "EARN_ORDER",
  "pureAmount": 50000,
  "orderId": 102
}

### 2.1 주문 반품
POST http://localhost:9002/internal/points/earn
Content-Type: application/json

{
  "memberId": 1,
  "eventType": "EARN_REFUND",
  "pureAmount": 5000,
  "orderId": 102
}

### 2.2 일반 리뷰 적립 (200 포인트)
POST http://localhost:9002/internal/points/earn
Content-Type: application/json

{
  "memberId": 1,
  "eventType": "EARN_REVIEW"
}

### 2.3 사진 리뷰 적립 (500 포인트)
POST http://localhost:9002/internal/points/earn
Content-Type: application/json

{
  "memberId": 1,
  "eventType": "EARN_PHOTO_REVIEW"
}


### 2.4 회원가입 적립 (5000 포인트)
POST http://localhost:9002/internal/points/earn
Content-Type: application/json

{
  "memberId": 1,
  "eventType": "EARN_SIGNUP"
}



### 3. 내 포인트 잔액 조회
GET http://localhost:8082/api/points/balance
Authorization: Bearer {{access_token}}

### 3.1. 내 포인트 이력 조회 (기본값: 0페이지, 10개)
GET http://localhost:8082/api/points/history
Authorization: Bearer {{access_token}}
Content-Type: application/json

### 3.2. 내 포인트 이력 조회 (페이징 테스트)
GET http://localhost:9002/api/points/history?page=5&size=10
X-USER-ID: 1

### 3.3. 없는 유저 조회 테스트 (예외 발생)
GET http://localhost:9002/api/points/balance
X-USER-ID: 99999



### 관리자 권한으로 100번 유저에게 5만 포인트 지급
POST http://localhost:8082/member/api/admin/points/adjustment
Content-Type: application/json

{
  "memberId": 2,
  "amount": 50000,
  "reason": "테스트용 용돈 지급"
}

### 4. 현재 포인트 정책 조회
GET http://localhost:9002/api/admin/points/policy

### 4.1. 포인트 정책 변경 (update)
POST http://localhost:9002/api/admin/points/policy
Content-Type: application/json

{
  "signupPoint": 10000,
  "reviewPoint": 5000,
  "photoPoint": 1000
}




### 5. 관리자 수동 포인트 지급
POST http://localhost:9002/api/admin/points/adjustment
Content-Type: application/json

{
  "memberId": 5,
  "amount": 3000,
  "reason": "배송 지연 보상금"
}

### 16. 관리자 수동 포인트 차감
POST http://localhost:9002/api/admin/points/adjustment
Content-Type: application/json
X-USER-ID: 999

{
  "memberId": 1,
  "amount": -500,
  "reason": "시스템 오류로 지급된 포인트 회수"
}

### 17. 관리자 수동 차감 실패 (잔액 부족)
POST http://localhost:9002/api/admin/points/adjustment
Content-Type: application/json
X-USER-ID: 999

{
  "memberId": 1,
  "amount": -999999999,
  "reason": "악성 유저 포인트 차감"
}